### ISSUE TITLE
Cannot launch Marp CLI standalone binary

### ISSUE THREAD

**Issue by lyc-Lacewing** [marp-team/marp-cli#505] opened 2023-02-21 00:52 UTC
### Version of Marp Tool

Marp CLI 2.4.0

### Operating System

Windows

### Environment

Windows 10, with Edge and Chrome installed, but without Node.js

### How to reproduce

1. Download the [latest standalone binary](https://github.com/marp-team/marp-cli/releases/tag/v2.4.0) of Marp CLI (marp-cli-v2.4.0-win.zip)
2. Unzip the downloaded `.zip` file
3. Run the `.exe`

### Expected behavior

Some Marp CLI interfaces show up where I can input Markdown content as shown in [the GIF](https://raw.githubusercontent.com/marp-team/marp-cli/main/docs/images/marp-cli.gif).

### Actual behavior

A command line window appeared and disappeared after few seconds. No text was seen in the command line window. No process named 'marp' was shown in Task Manager.

### Additional information

In `README` I saw 

> no need to install Node.js separately

so I didn't install Node.js.

**Comment by yhatt** [comment] 2023-02-21 11:38
A standalone binary is "the executable CLI". It's not meaning "the GUI frontend of CLI".

Commonly CLI executables must be called from a console such as `cmd.exe`, not a file explorer. That's a matter in any CLI tool. (e.g. the process of `ffmpeg.exe` CLI will close immediately if tried to launch it by dobule click)

Close this because it's a generality, not a bug.

**Closed by yhatt** 2023-02-21 11:38 UTC
Labels: question 🙅
