### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by dagostinelli** [marp-team/marp-cli#336] opened 2021-04-22 20:58 UTC
All of a sudden, out of nowhere, it doesn't work:

```
$ npx @marp-team/marp-cli -s .
npx: installed 270 in 12.193s
Unexpected token 'export'
```

I'm guessing a dependency failed.

**Comment by yhatt** [comment] 2021-04-24 12:43
Currently I have not confirmed that error. Probably already fixed by updation for deep-dependent package.

If you've still met the error, try cleaning npx cache: [`rm -rf ~/.npm/_npx` for npm v6](https://stackoverflow.com/a/66019858) and `npm cache clean --force` for npm v7. And you can use an already packaged standalone binary too. (https://github.com/marp-team/marp-cli/releases)

Close this because actually Marp CLI cannot do anything for that.

**Closed by yhatt** 2021-04-24 12:43 UTC
