### ISSUE TITLE
marp-cli binary

### ISSUE THREAD

**Issue by Hermann12** [marp-team/marp-cli#126] opened 2019-07-12 17:39 UTC
V0.12.0: Program open the window and closed directly under windows10 (64)

**Comment by yhatt** [comment] 2019-07-12 18:02
I cannot reproduce in Windows 10 (64bit). What do you see when opening CLI through PowerShell?

**Comment by Hermann12** [comment] 2019-07-12 18:32
Win10 V1903: First I started on USB stick, now I repeat the test and copy direkt to C:/ unfortunatly with the same result. Windows open shortly, I can imagin some comands and then the window closed directly.

**Comment by yhatt** [comment] 2019-07-12 19:24
Don't open with double click. Thats result is natural because Marp CLI is not GUI tool as name suggests. In Windows, it's better using PowerShell or command prompt.

We close this because it's not essential issue of Marp CLI.

**Closed by yhatt** 2019-07-12 19:24 UTC

**Comment by Hermann12** [comment] 2019-07-12 19:33
Solved, Thanks, it works now. I have to start with .\marp.exe in powershell. Can I change the text color on the slides?

**Comment by yhatt** [comment] 2019-07-12 20:08
💁‍♂️ https://github.com/marp-team/marpit/issues/162

**Comment by Hermann12** [comment] 2019-07-12 21:25
Thanks this is a part of my question. My wish is more change the text color for the whole document.

**Comment by yhatt** [comment] 2019-07-13 09:35
OK, let's try to use [`color` directive](https://marpit.marp.app/directives?id=local-directives-1).

```markdown
---
color: red
---

Your contents are here...
```
