### ISSUE TITLE
marp stuck a long time without any output

### ISSUE THREAD

**Issue by kongdd** [marp-team/marp-cli#561] opened 2023-11-13 14:37 UTC
### Version of Marp Tool

@marp-team/marp-cli v3.4.0 (w/ @marp-team/marp-core v3.9.0)

### Operating System

Windows

### Environment

- OS version: win10
- Node.js: 20.9

### How to reproduce

> slider-deck.md
```md
---
theme: uncover
---

# hello
```

```ps
marp --pdf slide-deck.md
# [  INFO ] Converting 1 markdown...
```

### Expected behavior

generate pdf

### Actual behavior

no response

**Comment by kongdd** [comment] 2023-11-13 14:42
The version 3.3.0 works. While the latest not.

**Comment by yhatt** [comment] 2023-11-13 15:23
Similar: https://github.com/marp-team/marp-vscode/issues/448

The Chromium browser might be getting stuck while spawning by Puppeteer. What CLI logs will be output if set `DEBUG` env as `puppeteer:*`?

```
set DEBUG=puppeteer:*
marp --pdf slide-deck.md
```

**Comment by yhatt** [comment] 2023-12-03 09:02
We are temporarily closing this issue until additional information necessary for verification and reproduction is provided. If the problem persists, please reopen this issue with the required information.

**Closed by yhatt** 2023-12-03 09:02 UTC
Labels: need more info

**Comment by nagromc** [comment] 2023-12-29 10:11
Same problem here.

# Input

`slides.md`
```md
---
marp: true
---

# hello
```

# Console output

```shell
marp --pdf slides.md
(node:9589) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[  INFO ] Converting 1 markdown...
```

But it hangs out indefinitely.

# Environment

macOS Sonoma 14.2.1 (23C71)
Node.js v21.4.0
marp-cli v3.4.0

**Comment by yhatt** [comment] 2023-12-29 10:15
Have installed the latest version of Chrome? Recent Puppeteer that the current Marp CLI is using may not compatible with previous Chrome versions due to the change of automation protocol for Chrome.
https://developer.chrome.com/blog/puppeteer-webdriver-bidi-2023

**Comment by yz4322gly** [comment] 2024-07-02 08:26
yes!
i use  this cmd :
set DEBUG=puppeteer:* marp --pdf slide-deck.md 
Find a suspicious file path
C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe
this appliaction cant open , and than delete it. 
reinstall laster chrome
and retry ok.
